export type Book = {
  title: string
  author: string
  note?: string
  isbn?: string
  affiliateUrl?: string // ready for future affiliate links
}

export type LibraryCategory = {
  id: string
  label: string
  description: string
  books: Book[]
}

export const library: LibraryCategory[] = [
  {
    id: 'ideas',
    label: 'Ideas & Society',
    description: "Books that changed how I think about people, systems, and what's possible.",
    books: [
      {
        title: 'Humankind: A Hopeful History',
        author: 'Rutger Bregman',
        isbn: '9780316418522',
        note: "The most persuasive case I've read that humans are fundamentally decent — and that our institutions haven't caught up.",
      },
      {
        title: 'Utopia for Realists',
        author: 'Rutger Bregman',
        isbn: '9780316471916',
        note: 'Universal basic income, the 15-hour work week, open borders. Bregman makes the radical feel inevitable.',
      },
      {
        title: 'Sapiens',
        author: 'Yuval Noah Harari',
        isbn: '9780062316097',
        note: 'The sweep of human history in 400 pages. Harari is never neutral, which is exactly what makes him worth reading.',
      },
      {
        title: 'Thinking, Fast and Slow',
        author: 'Daniel Kahneman',
        isbn: '9780374533557',
        note: 'The two-system model of the mind. Changed how I catch myself making decisions.',
      },
      {
        title: 'Prosperity',
        author: 'Colin Mayer',
        isbn: '9780198824114',
        note: 'What corporations are actually for, and how they could be redesigned to serve people rather than just shareholders.',
      },
      {
        title: 'How Minds Change',
        author: 'David McRaney',
        isbn: '9780593190463',
        note: 'Why deeply held beliefs shift, and the psychology underneath every conversion story.',
      },
      {
        title: 'The WEIRDest People in the World',
        author: 'Joseph Henrich',
        isbn: '9780374710453',
        note: 'How Western, Educated, Industrialised, Rich and Democratic societies became the global psychological outlier.',
      },
      {
        title: 'The Status Game',
        author: 'Will Storr',
        isbn: '9780008311377',
        note: 'Status is the hidden engine of almost everything humans do. Storr maps the game we all play without naming it.',
      },
      {
        title: 'Noise: A Flaw in Human Judgment',
        author: 'Daniel Kahneman, Olivier Sibony & Cass Sunstein',
        isbn: '9780316451406',
        note: "We talk about bias constantly and ignore noise entirely. Kahneman's follow-up to Thinking, Fast and Slow lands harder.",
      },
      {
        title: 'The Crowd',
        author: 'Gustave Le Bon',
        isbn: '9780140446043',
        note: 'Written in 1895 and still the sharpest account of what happens to individual judgment inside a mob.',
      },
      {
        title: 'Behave',
        author: 'Robert Sapolsky',
        isbn: '9780143110910',
        note: 'Why humans do what they do — from neurons firing in the second before an action to the evolutionary pressures behind it. Enormous and worth every page.',
      },
      {
        title: 'The Righteous Mind',
        author: 'Jonathan Haidt',
        isbn: '9780307455772',
        note: 'Moral intuitions come first, reasoning comes second. Haidt explains why talking people out of their politics almost never works.',
      },
      {
        title: 'Factfulness',
        author: 'Hans Rosling',
        isbn: '9781250107817',
        note: 'The world is better than your instincts tell you, and Rosling proves it with data. The most optimistic rigorous book I know.',
      },
      {
        title: 'The Elephant in the Brain',
        author: 'Kevin Simler & Robin Hanson',
        isbn: '9780190495992',
        note: 'Most of what we do is signalling, not the thing we say it is. Uncomfortable and illuminating.',
      },
      {
        title: 'Seeing Like a State',
        author: 'James C. Scott',
        isbn: '9780300078152',
        note: 'How governments simplify the world into legible categories — and why those simplifications keep failing the people inside them.',
      },
    ],
  },
  {
    id: 'design',
    label: 'Design',
    description: 'How things are shaped, why that matters, and the invisible decisions behind every object and interface.',
    books: [
      {
        title: 'The Design of Everyday Things',
        author: 'Don Norman',
        isbn: '9780465050659',
        note: 'Every bad door handle is a design failure. Norman makes you see affordances and feedback loops everywhere.',
      },
      {
        title: 'Thinking with Type',
        author: 'Ellen Lupton',
        isbn: '9781568989693',
        note: 'The clearest introduction to typography I have found. Practical, well-designed, used regularly.',
      },
      {
        title: 'The Elements of Typographic Style',
        author: 'Robert Bringhurst',
        isbn: '9780881792126',
        note: "The typographer's bible. Dense and precise — read slowly.",
      },
      {
        title: 'Grid Systems in Graphic Design',
        author: 'Josef Müller-Brockmann',
        isbn: '9783721201451',
        note: 'The canonical text on systematic layout. Every grid you have ever used traces back to this.',
      },
      {
        title: "Don't Make Me Think",
        author: 'Steve Krug',
        isbn: '9780321965516',
        note: 'The thinnest, most useful UX book. Takes two hours to read and saves years of over-engineering.',
      },
      {
        title: 'How Buildings Learn',
        author: 'Stewart Brand',
        isbn: '9780140139969',
        note: 'Architecture as a time-based medium. The six pace layers model applies far beyond buildings.',
      },
      {
        title: 'Designing with the Mind in Mind',
        author: 'Jeff Johnson',
        isbn: '9780124079144',
        note: 'Cognitive psychology translated directly into interface design principles.',
      },
      {
        title: 'Ruined by Design',
        author: 'Mike Monteiro',
        isbn: '9781090532763',
        note: 'Design is never neutral. Monteiro argues that designers need to own the consequences of what they ship.',
      },
      {
        title: 'Speculative Everything',
        author: 'Anthony Dunne & Fiona Raby',
        isbn: '9780262019842',
        note: 'Design as a tool for imagining alternative futures, not just solving present problems. Changed how I think about briefs.',
      },
      {
        title: 'The Architecture of Happiness',
        author: 'Alain de Botton',
        isbn: '9780307277817',
        note: 'Why the spaces we inhabit shape who we are. Philosophy dressed as art criticism — readable and sharp.',
      },
      {
        title: 'Emotional Design',
        author: 'Don Norman',
        isbn: '9780465051366',
        note: "The sequel to Everyday Things, focused on why beautiful things work better. Norman's visceral/behavioural/reflective framework is genuinely useful.",
      },
      {
        title: 'logo modernism',
        author: 'Jens Müller',
        isbn: '9783836548830',
        note: '6,000 logos from 1940–1980. The kind of reference book you open for five minutes and lose an hour in.',
      },
      {
        title: 'Zag',
        author: 'Marty Neumeier',
        isbn: '9780321426772',
        note: 'A brand is a gut feeling. Short, fast, and more rigorous than its length suggests.',
      },
      {
        title: 'The Vignelli Canon',
        author: 'Massimo Vignelli',
        isbn: '9783037782248',
        note: "Vignelli's principles in his own words. Semantic, syntactic, pragmatic — a framework I keep returning to.",
      },
      {
        title: 'Information Dashboard Design',
        author: 'Stephen Few',
        isbn: '9781938377006',
        note: "The single best resource on displaying data clearly. Every dashboard I've built since is better for it.",
      },
    ],
  },
  {
    id: 'product',
    label: 'Product & Strategy',
    description: 'The craft of deciding what to build and why — from discovery through to market.',
    books: [
      {
        title: 'Continuous Discovery Habits',
        author: 'Teresa Torres',
        isbn: '9781736633304',
        note: 'The most practical product discovery framework I have encountered. Opportunity trees changed how I structure problems.',
      },
      {
        title: 'Inspired',
        author: 'Marty Cagan',
        isbn: '9781119387503',
        note: 'The product management canon. Cagan is blunt about what separates real product work from feature factories.',
      },
      {
        title: 'Competing Against Luck',
        author: 'Clayton Christensen',
        isbn: '9780062435613',
        note: 'Jobs-to-be-done theory explained by its originator. Progress, not products, is what people hire for.',
      },
      {
        title: 'Good Strategy Bad Strategy',
        author: 'Richard Rumelt',
        isbn: '9780307886231',
        note: 'Strategy as diagnosis + guiding policy + coherent actions. Most "strategy" documents fail all three tests.',
      },
      {
        title: 'The Lean Startup',
        author: 'Eric Ries',
        isbn: '9780307887894',
        note: 'Build-measure-learn. The vocabulary became so widespread it is easy to forget how much it shifted practice.',
      },
      {
        title: "The Innovator's Dilemma",
        author: 'Clayton Christensen',
        isbn: '9780062060242',
        note: 'Why great companies fail despite doing everything right. Disruption theory in its original, unmuddied form.',
      },
      {
        title: 'Empowered',
        author: 'Marty Cagan & Chris Jones',
        isbn: '9781119691266',
        note: "The companion to Inspired, focused on teams rather than individuals. The difference between missionaries and mercenaries.",
      },
      {
        title: 'The Mom Test',
        author: 'Rob Fitzpatrick',
        isbn: '9781492180746',
        note: 'How to talk to customers without them lying to you — because everyone lies when they want to be polite. Short and precise.',
      },
      {
        title: 'Obviously Awesome',
        author: 'April Dunford',
        isbn: '9781999023003',
        note: 'Positioning is the foundation everything else sits on. Dunford gives it a framework that actually works in practice.',
      },
      {
        title: 'Escaping the Build Trap',
        author: 'Melissa Perri',
        isbn: '9781491973790',
        note: 'Product management as a discipline versus a role. The build trap is where output replaces outcomes.',
      },
      {
        title: 'Crossing the Chasm',
        author: 'Geoffrey Moore',
        isbn: '9780062292988',
        note: 'The gap between early adopters and the mainstream is where most startups die. Moore named it and mapped the bridge.',
      },
      {
        title: 'Shape Up',
        author: 'Ryan Singer',
        isbn: '9780578225296',
        note: "Basecamp's alternative to sprints and backlogs — appetite, shaping, and six-week cycles. Worth reading even if you don't adopt it wholesale.",
      },
      {
        title: 'Working Backwards',
        author: 'Colin Bryar & Bill Carr',
        isbn: '9781250267597',
        note: "How Amazon builds. Press release before product, single-threaded owners, the six-page memo — all explained from the inside.",
      },
      {
        title: 'Zero to One',
        author: 'Peter Thiel',
        isbn: '9780804139021',
        note: 'Competition is for losers. Thiel is often wrong but always worth arguing with.',
      },
      {
        title: 'The Cold Start Problem',
        author: 'Andrew Chen',
        isbn: '9780062969743',
        note: 'Network effects from the inside — how products actually bootstrap from nothing to something. Better than anything else on the subject.',
      },
    ],
  },
  {
    id: 'engineering',
    label: 'Engineering & Systems',
    description: "How to build things that last, scale, and don't quietly rot.",
    books: [
      {
        title: 'A Philosophy of Software Design',
        author: 'John Ousterhout',
        isbn: '9781732102200',
        note: "Complexity is the enemy. Ousterhout's module depth principle reshaped how I think about interfaces.",
      },
      {
        title: 'Designing Data-Intensive Applications',
        author: 'Martin Kleppmann',
        isbn: '9781449373320',
        note: 'The distributed systems textbook that reads like a conversation. Indispensable for anything at scale.',
      },
      {
        title: 'The Pragmatic Programmer',
        author: 'Hunt & Thomas',
        isbn: '9780135957059',
        note: 'Career-shaping advice for engineers. The tracer bullet and broken windows chapters still come to mind regularly.',
      },
      {
        title: 'The Phoenix Project',
        author: 'Gene Kim',
        isbn: '9780988262508',
        note: 'DevOps as a novel. Surprisingly readable and the three ways framing is genuinely useful.',
      },
      {
        title: 'Clean Code',
        author: 'Robert C. Martin',
        isbn: '9780132350884',
        note: 'Some of it is dated, all of it is worth arguing with. Code that reads like prose is still the goal.',
      },
      {
        title: 'Structure and Interpretation of Computer Programs',
        author: 'Abelson & Sussman',
        isbn: '9780262510875',
        note: 'SICP. The most intellectually demanding programming book — and the most rewarding.',
      },
      {
        title: 'Thinking in Systems',
        author: 'Donella Meadows',
        isbn: '9781603580557',
        note: 'Stocks, flows, feedback loops, and leverage points. The mental models that make complex systems legible.',
      },
      {
        title: 'Software Engineering at Google',
        author: 'Titus Winters, Tom Manshreck & Hyrum Wright',
        isbn: '9781492082798',
        note: "How Google thinks about code at scale — time, change, and trade-offs. The 'Hyrum's Law' framing alone is worth it.",
      },
      {
        title: 'An Elegant Puzzle',
        author: 'Will Larson',
        isbn: '9781732265189',
        note: 'Engineering management from someone who has done it at scale. Honest about the parts that are just hard.',
      },
      {
        title: 'The Staff Engineer\'s Path',
        author: 'Tanya Reilly',
        isbn: '9781098118730',
        note: 'What it means to be a senior technical contributor without moving into management. A map for a role with no formal definition.',
      },
      {
        title: 'Site Reliability Engineering',
        author: 'Beyer, Jones, Petoff & Murphy',
        isbn: '9781491929124',
        note: "Google's SRE book. Error budgets, SLOs, toil — the vocabulary of running systems that matter.",
      },
      {
        title: 'Release It!',
        author: 'Michael Nygard',
        isbn: '9781680502398',
        note: 'Production systems fail in patterns. Circuit breakers, bulkheads, timeouts — this is where the vocabulary comes from.',
      },
      {
        title: 'The Mythical Man-Month',
        author: 'Fred Brooks',
        isbn: '9780201835953',
        note: 'Adding people to a late project makes it later. Still the most cited truth in software, still ignored in practice.',
      },
      {
        title: 'Database Internals',
        author: 'Alex Petrov',
        isbn: '9781492040347',
        note: 'Storage engines, B-trees, LSM trees, distributed consensus — the machinery under every database explained clearly.',
      },
      {
        title: 'Accelerate',
        author: 'Nicole Forsgren, Jez Humble & Gene Kim',
        isbn: '9781942788331',
        note: 'The research behind what makes software teams perform. DORA metrics with the data to back them up.',
      },
    ],
  },
  {
    id: 'technology',
    label: 'Technology & Future',
    description: 'The arc of computing — where it came from, what it is doing to us, where it might go.',
    books: [
      {
        title: 'The Innovators',
        author: 'Walter Isaacson',
        isbn: '9781476708706',
        note: 'The history of the digital revolution as a story about collaboration. Ada Lovelace to the internet.',
      },
      {
        title: 'The Second Machine Age',
        author: 'Brynjolfsson & McAfee',
        isbn: '9780393350647',
        note: 'How digital technology is reshaping work, wages, and what human contribution actually means.',
      },
      {
        title: 'Superintelligence',
        author: 'Nick Bostrom',
        isbn: '9780198739838',
        note: 'Dense, careful, alarming. The control problem framed before it was a mainstream concern.',
      },
      {
        title: 'Life 3.0',
        author: 'Max Tegmark',
        isbn: '9780307889560',
        note: 'What AI being smarter than humans actually implies — for power, meaning, and the shape of the future.',
      },
      {
        title: 'The Age of Surveillance Capitalism',
        author: 'Shoshana Zuboff',
        isbn: '9781610395694',
        note: 'Long, important, infuriating. Behavioural surplus as the raw material of a new economic logic.',
      },
      {
        title: 'The Shallows',
        author: 'Nicholas Carr',
        isbn: '9780393339758',
        note: 'What the internet is doing to our brains. The argument has only sharpened since 2010.',
      },
      {
        title: 'The Code Breaker',
        author: 'Walter Isaacson',
        isbn: '9781982115852',
        note: 'Jennifer Doudna, CRISPR, and the race to rewrite life. Science biography at its best.',
      },
      {
        title: 'The Coming Wave',
        author: 'Mustafa Suleyman',
        isbn: '9780593593950',
        note: "AI and synthetic biology arriving together. One of the people who built this explaining why containment is the problem of our era.",
      },
      {
        title: 'Power and Progress',
        author: 'Daron Acemoglu & Simon Johnson',
        isbn: '9781541702530',
        note: 'Technology does not automatically benefit everyone — who captures the gains is a political choice. A counterweight to techno-optimism.',
      },
      {
        title: 'The Alignment Problem',
        author: 'Brian Christian',
        isbn: '9780393635829',
        note: "The clearest explanation of what AI alignment actually means, told through the people trying to solve it. Less alarming than Bostrom, more grounded.",
      },
      {
        title: 'Hackers: Heroes of the Computer Revolution',
        author: 'Steven Levy',
        isbn: '9781449388393',
        note: "The hacker ethic, the MIT AI Lab, early Apple — the culture that built computing told by someone who was there.",
      },
      {
        title: 'The Dream Machine',
        author: 'M. Mitchell Waldrop',
        isbn: '9781732265110',
        note: "J.C.R. Licklider invented the internet before anyone knew what the internet was. The best tech biography I've read.",
      },
      {
        title: 'Weapons of Math Destruction',
        author: 'Cathy O\'Neil',
        isbn: '9780553418835',
        note: 'Algorithms that pretend to be objective while encoding the biases of whoever designed them. Clear, specific, and necessary.',
      },
      {
        title: 'The Master Switch',
        author: 'Tim Wu',
        isbn: '9780307390998',
        note: 'Every open communications technology eventually gets closed. Wu charts the cycle across radio, telephone, film, and internet.',
      },
      {
        title: 'A Thousand Brains',
        author: 'Jeff Hawkins',
        isbn: '9781541675797',
        note: 'A theory of intelligence that takes the structure of the neocortex seriously. Speculative but worth the argument.',
      },
    ],
  },
  {
    id: 'chess',
    label: 'Chess',
    description: 'The game that taught me how to think about positions, plans, and patience.',
    books: [
      {
        title: 'My System',
        author: 'Aron Nimzowitsch',
        isbn: '9781857441147',
        note: 'The most influential chess book ever written. Blockade, prophylaxis, the passed pawn — all codified here.',
      },
      {
        title: 'Chess Fundamentals',
        author: 'José Raúl Capablanca',
        isbn: '9780486280011',
        note: 'A world champion explaining the game simply. The endgame chapters alone justify the read.',
      },
      {
        title: 'How to Reassess Your Chess',
        author: 'Jeremy Silman',
        isbn: '9781890085131',
        note: 'Imbalances as the engine of chess thinking. Changed how I evaluate positions.',
      },
      {
        title: 'Think Like a Grandmaster',
        author: 'Alexander Kotov',
        isbn: '9780713400076',
        note: 'The candidate moves method. How strong players actually calculate — systematically, not by feel.',
      },
      {
        title: 'The Life and Games of Mikhail Tal',
        author: 'Mikhail Tal',
        isbn: '9781857442021',
        note: 'Tal annotating his own games with wit and honesty. The most entertaining chess book I have read.',
      },
      {
        title: 'Endgame',
        author: 'Frank Brady',
        isbn: '9780307463906',
        note: 'The definitive Fischer biography. Genius, paranoia, and the price of being singular.',
      },
      {
        title: '101 Chess Endgame Tips',
        author: 'Steve Giddins',
        isbn: '9781857445121',
        note: "Chess taught me how to think about positions that look equivalent but aren't. Endgames especially.",
      },
      {
        title: 'Zurich 1953',
        author: 'David Bronstein',
        isbn: '9780486238005',
        note: 'Game annotations as literature. Bronstein writes about chess the way a philosopher writes about life.',
      },
      {
        title: 'The Amateur\'s Mind',
        author: 'Jeremy Silman',
        isbn: '9781890085025',
        note: 'Silman diagnoses the thinking errors of club players by watching them think out loud. Humbling and instructive.',
      },
      {
        title: 'Dvoretsky\'s Endgame Manual',
        author: 'Mark Dvoretsky',
        isbn: '9781941270042',
        note: 'The serious endgame reference. Not light reading — but if you want to actually improve, this is where the work happens.',
      },
      {
        title: 'Kasparov on Kasparov: Part I',
        author: 'Garry Kasparov',
        isbn: '9781781940204',
        note: 'Kasparov annotating his own games from 1973 to 1985. The depth of analysis is extraordinary.',
      },
      {
        title: 'The Life and Games of Akiba Rubinstein',
        author: 'John Donaldson & Nikolay Minev',
        isbn: '9781888690057',
        note: 'Rubinstein never became world champion but his endgame technique remained the gold standard for a generation.',
      },
      {
        title: 'Art of Attack in Chess',
        author: 'Vladimir Vukovic',
        isbn: '9781857442403',
        note: 'The anatomy of kingside attacks, sacrifices, and mating patterns. Still the definitive text on attacking chess.',
      },
      {
        title: 'Logical Chess: Move by Move',
        author: 'Irving Chernev',
        isbn: '9780671619459',
        note: 'Every move explained. An ideal book for anyone learning to think in chess terms rather than just calculating lines.',
      },
      {
        title: 'Secrets of Modern Chess Strategy',
        author: 'John Watson',
        isbn: '9781901983012',
        note: 'How modern grandmasters broke the rules Nimzowitsch wrote and what replaced them. A genuine advance in chess understanding.',
      },
    ],
  },
  {
    id: 'fiction',
    label: 'Fiction',
    description: "Novels I've read and ones on the to-read pile. Mostly thrillers and crime.",
    books: [
      {
        title: 'Inferno',
        author: 'Dan Brown',
        isbn: '9780385537858',
        note: 'Overpopulation as the villain. Fast, propulsive, infuriating in the best way.',
      },
      {
        title: 'A Question of Blood',
        author: 'Ian Rankin',
        isbn: '9780752855776',
        note: 'Rebus at his most complicated. Rankin writes Edinburgh the way Chandler wrote LA.',
      },
      {
        title: 'Roots',
        author: 'Alex Haley',
        isbn: '9780385037166',
        note: 'One of the most important novels written in English. Haley traced his lineage back seven generations to The Gambia.',
      },
      {
        title: 'Things Fall Apart',
        author: 'Chinua Achebe',
        isbn: '9780385474542',
        note: 'The novel that made African literature visible to the world. Okonkwo is unforgettable.',
      },
      {
        title: 'Half of a Yellow Sun',
        author: 'Chimamanda Ngozi Adichie',
        isbn: '9781400044160',
        note: 'The Biafran War refracted through three lives. Devastating and precise.',
      },
      {
        title: '1984',
        author: 'George Orwell',
        isbn: '9780451524935',
        note: "The vocabulary — doublethink, memory hole, unperson — has become the only way to describe what it describes.",
      },
      {
        title: 'One Head Too Many',
        author: 'Christopher Brookmyre',
        isbn: '9780349117904',
        note: "Brookmyre's Scotland is darkly funny in a way that sneaks up on you.",
      },
      {
        title: 'The Girl with the Dragon Tattoo',
        author: 'Stieg Larsson',
        isbn: '9780307454546',
        note: 'Lisbeth Salander is the most compelling crime fiction character of the 2000s. The Swedish winter drips off every page.',
      },
      {
        title: 'No Longer at Ease',
        author: 'Chinua Achebe',
        isbn: '9780385474559',
        note: "The sequel to Things Fall Apart, set in colonial Lagos. Obi Okonkwo's disintegration is quiet and brutal.",
      },
      {
        title: 'The Lincoln Lawyer',
        author: 'Michael Connelly',
        isbn: '9780316734936',
        note: "Connelly's best standalone. Mickey Haller working cases from the back of a Lincoln is one of crime fiction's great setups.",
      },
      {
        title: 'Americanah',
        author: 'Chimamanda Ngozi Adichie',
        isbn: '9780307455925',
        note: 'Race, identity, and belonging told through a love story that moves between Nigeria, the UK, and the US. Sharp and honest.',
      },
      {
        title: 'The Name of the Rose',
        author: 'Umberto Eco',
        isbn: '9780544176560',
        note: 'A medieval murder mystery that is also an essay on semiotics and the nature of knowledge. Nobody else could have written it.',
      },
      {
        title: 'Brave New World',
        author: 'Aldous Huxley',
        isbn: '9780060850524',
        note: 'The dystopia where everything is fine and everyone is happy and that is precisely the problem. Aged better than Orwell.',
      },
      {
        title: 'The Spy Who Came in from the Cold',
        author: 'John le Carré',
        isbn: '9780143124344',
        note: 'The definitive Cold War novel. Le Carré strips the glamour from intelligence work and replaces it with compromise and shame.',
      },
      {
        title: 'Purple Hibiscus',
        author: 'Chimamanda Ngozi Adichie',
        isbn: '9781616202415',
        note: "Adichie's debut. Silence, violence, and faith in a Nigerian household. The restraint is what makes it devastating.",
      },
    ],
  },
  {
    id: 'history',
    label: 'History & Conflict',
    description: 'Mostly 20th century — war, intelligence, and the machinery of states.',
    books: [
      {
        title: 'The Secret War',
        author: 'Max Hastings',
        isbn: '9780007503926',
        note: 'Intelligence in World War II — signals, deception, and the people who ran both. Meticulously researched.',
      },
      {
        title: 'The Guns of August',
        author: 'Barbara Tuchman',
        isbn: '9780345386236',
        note: 'How a continent sleepwalked into catastrophe in 1914. The clarity of hindsight makes it almost unbearable.',
      },
      {
        title: 'Bloodlands',
        author: 'Timothy Snyder',
        isbn: '9780465002399',
        note: 'The killing fields between Hitler and Stalin. The most important history book of the last twenty years.',
      },
      {
        title: 'Empire of Pain',
        author: 'Patrick Radden Keefe',
        isbn: '9780385545686',
        note: 'The Sackler family and the opioid crisis. Corporate accountability as narrative journalism.',
      },
      {
        title: 'The Secret War with Germany',
        author: 'David Kahn',
        isbn: '9780815409441',
        note: 'Espionage, disinformation, and the quiet battles fought away from any front line.',
      },
      {
        title: 'Unholy War',
        author: 'John L. Esposito',
        isbn: '9780195154351',
        note: 'A serious, non-polemical account of political Islam and how the West keeps misreading it.',
      },
      {
        title: 'The Storm of War',
        author: 'Andrew Roberts',
        isbn: '9780061228599',
        note: "The best single-volume account of World War II I've found. Roberts is never dull and always precise about why decisions were made.",
      },
      {
        title: 'The Rise and Fall of the Third Reich',
        author: 'William L. Shirer',
        isbn: '9781451651683',
        note: 'A thousand pages that feel necessary. Shirer was there for part of it, which gives the early chapters a texture no archive can replicate.',
      },
      {
        title: 'Say Nothing',
        author: 'Patrick Radden Keefe',
        isbn: '9780385521222',
        note: 'The Troubles in Northern Ireland told through one disappearance. Keefe is the best longform journalist writing today.',
      },
      {
        title: 'Ordinary Men',
        author: 'Christopher Browning',
        isbn: '9780062303028',
        note: 'How ordinary German police reservists became mass killers. The most uncomfortable history book I have read.',
      },
      {
        title: 'The Looming Tower',
        author: 'Lawrence Wright',
        isbn: '9780375414862',
        note: 'Al-Qaeda and the road to 9/11. Wright reconstructs the intelligence failures with novelistic precision.',
      },
      {
        title: 'Churchill: Walking with Destiny',
        author: 'Andrew Roberts',
        isbn: '9780670025770',
        note: 'The definitive Churchill biography. Roberts had access to the family diaries and it shows.',
      },
      {
        title: 'Postwar',
        author: 'Tony Judt',
        isbn: '9780143037750',
        note: 'Europe from 1945 to 2005. The scope is vast and the argument is controlled. Nobody else could have written it.',
      },
      {
        title: 'The Spy and the Traitor',
        author: 'Ben Macintyre',
        isbn: '9780385540780',
        note: "The Oleg Gordievsky story. Macintyre writes intelligence history better than anyone — the tension is real even when you know the ending.",
      },
      {
        title: 'Destined for War',
        author: 'Graham Allison',
        isbn: '9780544935273',
        note: "Thucydides' Trap applied to US-China. Whether or not you accept the thesis, the framework reshapes how you read geopolitics.",
      },
    ],
  },
  {
    id: 'leadership',
    label: 'Leadership & Business',
    description: 'The ones that earned their place by being specific, not by being motivational.',
    books: [
      {
        title: 'High Output Management',
        author: 'Andy Grove',
        isbn: '9780679762881',
        note: 'The most honest book on management I have read. Grove writes from inside the problem, not above it.',
      },
      {
        title: 'The Hard Thing About Hard Things',
        author: 'Ben Horowitz',
        isbn: '9780062273208',
        note: 'Business books rarely talk about being scared. This one does, and it is more useful for it.',
      },
      {
        title: 'The 8th Habit',
        author: 'Stephen R. Covey',
        isbn: '9780743206839',
        note: 'Beyond effectiveness to meaning. Where the 7 Habits ends, this begins.',
      },
      {
        title: 'Pour Your Heart Into It',
        author: 'Howard Schultz',
        isbn: '9780786863020',
        note: 'The Starbucks origin story — more honest about failure than most founder memoirs.',
      },
      {
        title: 'No Rules Rules',
        author: 'Reed Hastings',
        isbn: '9781984877864',
        note: 'How Netflix built a culture of freedom and responsibility. The keeper test is uncomfortable for a reason.',
      },
      {
        title: 'Experiencing LeaderShift',
        author: 'Don Cousins',
        isbn: '9780830827305',
        note: 'On the transition from leading through position to leading through influence.',
      },
      {
        title: 'The Effective Executive',
        author: 'Peter Drucker',
        isbn: '9780060833459',
        note: 'Effectiveness is a discipline, not a talent. Drucker published this in 1967 and it has not dated.',
      },
      {
        title: 'Trillion Dollar Coach',
        author: 'Schmidt, Rosenberg & Eagle',
        isbn: '9780062839268',
        note: "Bill Campbell coached Google, Apple, and Intuit without most people knowing his name. The best book on what coaching actually is.",
      },
      {
        title: 'The Ride of a Lifetime',
        author: 'Robert Iger',
        isbn: '9780399592096',
        note: 'Disney from the inside. Iger on acquiring Pixar, Marvel, and Lucasfilm is as good as business memoir gets.',
      },
      {
        title: 'Shoe Dog',
        author: 'Phil Knight',
        isbn: '9781501135927',
        note: 'Nike built from scratch. One of the best founder stories written — honest about luck, failure, and the deals that nearly broke everything.',
      },
      {
        title: 'Principles',
        author: 'Ray Dalio',
        isbn: '9781501124020',
        note: 'Long but worth it for the mental models. Radical transparency and the idea meritocracy are worth understanding even if you disagree.',
      },
      {
        title: 'Built to Last',
        author: 'Jim Collins & Jerry Porras',
        isbn: '9780060516406',
        note: "The visionary companies study. Some of it hasn't held up but the BHAG concept and clock-building vs. time-telling remain useful.",
      },
      {
        title: 'The Startup of You',
        author: 'Reid Hoffman & Ben Casnocha',
        isbn: '9780307888907',
        note: 'Career as a permanent beta. The ABZ planning framework is practical and the pivot concept applies well beyond startups.',
      },
      {
        title: 'Dare to Lead',
        author: 'Brené Brown',
        isbn: '9780399592522',
        note: 'Vulnerability as a leadership practice, not a weakness. Better than the TED talk — more specific and less polished, which makes it more useful.',
      },
      {
        title: 'The Alliance',
        author: 'Reid Hoffman, Ben Casnocha & Chris Yeh',
        isbn: '9781625275776',
        note: 'The employer-employee relationship reimagined as a mutual alliance with defined tours of duty. Honest about what loyalty actually means now.',
      },
    ],
  },
  {
    id: 'music',
    label: 'Music',
    description: 'Jazz lives here.',
    books: [
      {
        title: 'Jazz Singing',
        author: 'Will Friedwald',
        isbn: '9780306809781',
        note: 'The definitive guide to jazz vocals — Ella, Billie, Sinatra, and everyone they influenced. Dense and wonderful.',
      },
      {
        title: 'Kind of Blue',
        author: 'Ashley Kahn',
        isbn: '9780306810671',
        note: 'The making of the best-selling jazz album ever recorded. Kahn reconstructs sessions from the inside out.',
      },
      {
        title: 'Miles: The Autobiography',
        author: 'Miles Davis',
        isbn: '9780671725823',
        note: "Miles in his own voice — unfiltered, contradictory, essential. Nobody tells their own story like this.",
      },
      {
        title: 'The Rest Is Noise',
        author: 'Alex Ross',
        isbn: '9780312427719',
        note: 'A century of classical music as social and political history. Changed how I listen.',
      },
      {
        title: 'Stomping the Blues',
        author: 'Albert Murray',
        isbn: '9780306813078',
        note: 'Blues as an aesthetic philosophy, not just a genre. Murray makes the case that the blues is the foundation of all American music.',
      },
      {
        title: 'How to Listen to Jazz',
        author: 'Ted Gioia',
        isbn: '9780465060955',
        note: 'The gentlest possible entry point. Gioia gives you the vocabulary without the gatekeeping.',
      },
      {
        title: 'The History of Jazz',
        author: 'Ted Gioia',
        isbn: '9780199897681',
        note: 'Comprehensive without being encyclopaedic. The best single-volume survey of where jazz came from and where it went.',
      },
      {
        title: 'Coltrane: The Story of a Sound',
        author: 'Ben Ratliff',
        isbn: '9780312427733',
        note: "How Coltrane's influence spread and mutated through everyone who came after. Less biography, more theory of influence.",
      },
      {
        title: 'Musicophilia',
        author: 'Oliver Sacks',
        isbn: '9781400033539',
        note: 'Music and the brain, told through case studies. Sacks turns neurology into literature.',
      },
      {
        title: 'Just Kids',
        author: 'Patti Smith',
        isbn: '9780060936228',
        note: "Patti Smith and Robert Mapplethorpe in New York. One of the best books about what it actually feels like to be an artist.",
      },
      {
        title: 'Blue: The Murder of Jazz',
        author: 'Eric Nisenson',
        isbn: '9780306808289',
        note: "A polemical argument that jazz was killed by its own gatekeepers. Worth reading even if — especially if — you disagree.",
      },
      {
        title: 'Ella Fitzgerald: A Biography of the First Lady of Jazz',
        author: 'Stuart Nicholson',
        isbn: '9780306813290',
        note: "The fullest account of Fitzgerald's life and recordings. Her range was never just technical.",
      },
      {
        title: 'In Search of the Cannonball',
        author: 'Bob Blumenthal',
        isbn: '9780306814624',
        note: "Julian 'Cannonball' Adderley's career as both a musician and a gateway into soul jazz. Essential if you love the Adderleys.",
      },
      {
        title: 'The Jazz Standards',
        author: 'Ted Gioia',
        isbn: '9780199937271',
        note: 'Two hundred standards, each with history and recommended recordings. A reference and a reading book at once.',
      },
      {
        title: 'Nat King Cole',
        author: 'Will Friedwald',
        isbn: '9780306809828',
        note: "The pianist before the singer, and the singer who erased the pianist. Friedwald recovers the full Cole.",
      },
    ],
  },
  {
    id: 'reference',
    label: 'Reference',
    description: 'Things I reach for, not read cover to cover.',
    books: [
      {
        title: 'Visual Dictionary',
        author: 'DK',
        isbn: '9780756665104',
        note: 'Every object, labelled. Indispensable for writing precisely about things.',
      },
      {
        title: 'The Chicago Manual of Style',
        author: 'University of Chicago Press',
        isbn: '9780226104201',
        note: 'When in doubt about punctuation, grammar, or citation — this settles it.',
      },
      {
        title: 'Roget\'s Thesaurus',
        author: 'Peter Mark Roget',
        isbn: '9780140515039',
        note: 'Organised by concept, not alphabetically. The original version is still more useful than the digital alternatives.',
      },
      {
        title: 'The Emotion Thesaurus',
        author: 'Angela Ackerman & Becca Puglisi',
        isbn: '9780615459290',
        note: 'Physical cues, internal sensations, and behaviours for 130 emotions. Useful for writing and for understanding people.',
      },
      {
        title: 'Bird by Bird',
        author: 'Anne Lamott',
        isbn: '9780385480017',
        note: "On writing, mostly, but really on persistence. The shitty first draft chapter gets quoted constantly because it's true.",
      },
      {
        title: 'On Writing Well',
        author: 'William Zinsser',
        isbn: '9780060891541',
        note: 'Nonfiction writing made rigorous. Clutter is the enemy and simplicity is the work.',
      },
      {
        title: 'The Sense of Style',
        author: 'Steven Pinker',
        isbn: '9780670025855',
        note: "A style guide grounded in linguistics rather than tradition. Pinker explains *why* the rules work, not just what they are.",
      },
      {
        title: 'Eats, Shoots & Leaves',
        author: 'Lynne Truss',
        isbn: '9781592400874',
        note: 'Punctuation written as polemic. Funnier than it has any right to be and genuinely useful.',
      },
      {
        title: 'The Synonym Finder',
        author: 'J.I. Rodale',
        isbn: '9780446370290',
        note: "The thickest synonym reference there is. When Roget doesn't have what you need, this does.",
      },
      {
        title: 'Strunk & White: The Elements of Style',
        author: 'William Strunk Jr. & E.B. White',
        isbn: '9780205313426',
        note: 'Seventy pages that changed how English prose is written. Still the first book to give any writer.',
      },
      {
        title: 'The Oxford Dictionary of Quotations',
        author: 'Oxford University Press',
        isbn: '9780199237173',
        note: 'The authoritative quotation reference. Worth owning in print — digital versions lose the serendipitous browsing.',
      },
      {
        title: 'Merriam-Webster\'s Collegiate Dictionary',
        author: 'Merriam-Webster',
        isbn: '9780877798095',
        note: 'The American standard. When spelling or definition needs settling, this is where it gets settled.',
      },
      {
        title: 'Made to Stick',
        author: 'Chip Heath & Dan Heath',
        isbn: '9781400064281',
        note: "Why some ideas survive and others die. The SUCCESs framework is a checklist worth running any communication through.",
      },
      {
        title: 'Writing Tools',
        author: 'Roy Peter Clark',
        isbn: '9780316014984',
        note: "50 strategies organised from nuts-and-bolts to big-picture. Clark's tool metaphor works — these are things you can pick up and use.",
      },
      {
        title: 'The War of Art',
        author: 'Steven Pressfield',
        isbn: '9781936891023',
        note: 'Resistance is the force that stops you from doing creative work. Naming it makes it easier to fight.',
      },
    ],
  },
]
